actor:
  _target_: fsres_sac_models.ReasoningStochasticActor
  layers_list:
    _target_: layers_utils.make_actor_layers
    action_size: ${action_size}
    output_extra_dims: ${action_size}
    modern: false
    num_hidden: 1
    dims: 256
    nonlinearity:
      _target_: layers_utils.tfl.ReLU
    init:
      _target_: layers_utils.tfi.Orthogonal
      gain: 1.414
    final_init:
      _target_: layers_utils.tfi.Orthogonal
      gain: 0.01414
    sn_hidden_layers: false
    parallel_models:
  norm_mean:
  norm_stddev:
  min_log_stddev: -10
  max_log_stddev: 2
  action_scale: ${action_scale}
  correct_logprob_for_action_scale: false